INSERT INTO `cargo`(`pkID`, `nombre`) VALUES (null, 'Coordinador'),(null, 'Rector'),(null, 'Personal de apoyo');


TRUNCATE TABLE grado;

INSERT INTO `grado`(`pkID`, `nombre`) VALUES (null, 'Transición'),(null, 'Primero'),(null, 'Segundo'), (null, 'Tercero'),(null, 'Cuarto'),(null, 'Quinto'),(null, 'Sexto'),(null, 'Séptimo'),(null, 'Octavo'),(null, 'Noveno'),(null, 'Décimo'),(null, 'Undécimo');


TRUNCATE TABLE `grupo_etnico`;

INSERT INTO `grupo_etnico`(`pkID`, `nombre`) VALUES 
(null, 'Achagua'),
(null, 'Amorua'),
(null, 'Andoque'),
(null,'Arhuaco'),
(null, 'Awa'),
(null, 'Bará'),
(null, 'Barazana'),
(null, 'Barí'),
(null, 'Betoye'),
(null, 'Bora'),
(null, 'Cabiyari'),
(null, 'Caramanta'),
(null, 'Carapana'),
(null, 'Carijona'),
(null, 'Chami'),
(null, 'Chimila'),
(null, 'Chiricoa'),
(null, 'Cocama'),
(null, 'Coconuco'),
(null, 'Cofán'),
(null, 'Corocoro'),
(null, 'Coyaima-Natagaima'),
(null, 'Cubeo'),
(null, 'Cuiba'),
(null, 'Curripaco'),
(null, 'Datuana'),
(null, 'Desano'),
(null, 'Dujos'),
(null, 'Embera'),
(null, 'Embera Catio'),
(null, 'Emberachami'),
(null, 'Emberasiapidara'),
(null, 'Garú'),
(null, 'Guambiano'),
(null, 'Guanaca'),
(null, 'Guayabero'),
(null, 'Guayuú'),
(null, 'Hitnú'),
(null, 'Inga'),
(null, 'Kamsa'),
(null, 'Katio'),
(null, 'Kogui'),
(null, 'Koreguaje'),
(null, 'Kurripako'),
(null, 'Letuama'),
(null, 'Macaguaje'),
(null, 'Macú'),
(null, 'Macuna'),
(null, 'Masiguare'),
(null, 'Matapi'),
(null, 'Miraña'),
(null, 'Muinane'),
(null, 'Muisca'),
(null, 'Mura'),
(null, 'Negritudes'),
(null, 'No Aplica'),
(null, 'Nonuya'),
(null, 'Nukak'),
(null, 'Ocaina'),
(null, 'Otras Etnias'),
(null, 'Paéz'),
(null, 'Pastos'),
(null,'Payoarini'),
(null,'Piapoco'),
(null,'Piaroa'),
(null,'Piratapuyo'),
(null,'Pisamira'),
(null,'Polindara'),
(null,'Puinabe'),
(null,'Puinave'),
(null,'Rom'),
(null,'Sáliba'),
(null,'Sikuani'),
(null,'Siona'),
(null,'Siriano'),
(null,'Siripu'),
(null,'Taiwano'),
(null,'Tama'),
(null,'TanimukA'),
(null,'Tariano'),
(null,'Tatuyo'),
(null,'Tikunas'),
(null,'Totoró'),
(null,'Tucano'),
(null,'Tule'),
(null,'Tuyuca'),
(null,'U´wa'),
(null,'Wanano'),
(null,'Wayuu'),
(null,'Witoto'),
(null,'Wiwua'),
(null,'Wounaan'),
(null,'Yagua'),
(null,'Yanacona'),
(null,'Yauna'),
(null,'Yucuna'),
(null,'Yuko'),
(null,'Yurí'),
(null,'Yurutí'),
(null,'Zenú');

